# Generated by Django 2.2.4 on 2019-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdprojeto', '0002_bdclientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdclientes',
            name='celular',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='bdclientes',
            name='cnpj',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
