# Generated by Django 2.2.4 on 2019-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdprojeto', '0003_auto_20190901_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdclientes',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='bdclientes',
            name='cnpj',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
