# Generated by Django 2.2.5 on 2019-11-04 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ativo', models.SmallIntegerField(blank=True, null=True)),
                ('nome', models.SmallIntegerField(blank=True, null=True)),
                ('valor', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bdclientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=30, null=True)),
                ('cnpj', models.CharField(max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('clinica_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomefantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('contato', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_cliente', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(blank=True, db_column='nome fantasia', max_length=50, null=True)),
                ('nome_juridico', models.CharField(blank=True, db_column='nome juridico', max_length=50, null=True)),
                ('cnpj', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_func', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nome', models.SmallIntegerField(blank=True, null=True)),
                ('nr_func', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('gestor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresNegativos',
            fields=[
                ('id', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('questao', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lucratividade',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('lucro_liquido_anual', models.SmallIntegerField(blank=True, null=True)),
                ('receita_total_anual', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passivos',
            fields=[
                ('id_passivo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nome', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roi',
            fields=[
                ('id', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('receita', models.SmallIntegerField(blank=True, null=True)),
                ('custo', models.SmallIntegerField(blank=True, null=True)),
                ('item', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaConversao',
            fields=[
                ('visitantes', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('id', models.SmallIntegerField(blank=True, null=True)),
                ('conversoes', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMedioVendas',
            fields=[
                ('id', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('total_receita', models.SmallIntegerField(blank=True, null=True)),
                ('total_vendas', models.SmallIntegerField(blank=True, null=True)),
                ('nr_compras', models.SmallIntegerField(blank=True, null=True)),
                ('periodo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.SmallIntegerField(blank=True, primary_key=True, serialize=False)),
                ('contratados', models.SmallIntegerField(blank=True, null=True)),
                ('desligamentos', models.SmallIntegerField(blank=True, null=True)),
                ('id_func_funcionarios', models.ForeignKey(blank=True, db_column='id_func_funcionarios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=9, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('id_cliente_empresas', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Empresas')),
            ],
        ),
    ]
