# Generated by Django 2.2.5 on 2019-11-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bdclientes',
            new_name='Clientes',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
