# Generated by Django 3.0.2 on 2020-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentabilidade',
            old_name='ano',
            new_name='data_fim',
        ),
        migrations.RemoveField(
            model_name='rentabilidade',
            name='mes',
        ),
        migrations.AddField(
            model_name='rentabilidade',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentabilidade',
            name='rentabilidade',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
