# Generated by Django 3.0.2 on 2020-01-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200118_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ativos',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='IndicadoresNegativos',
        ),
        migrations.DeleteModel(
            name='Lucratividade',
        ),
        migrations.DeleteModel(
            name='Passivos',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.DeleteModel(
            name='Rentabilidade',
        ),
        migrations.DeleteModel(
            name='Roi',
        ),
        migrations.DeleteModel(
            name='TaxaConversao',
        ),
        migrations.DeleteModel(
            name='TicketMedioVendas',
        ),
    ]
