# Generated by Django 2.2.5 on 2019-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191104_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='funcionario_id',
            new_name='id_func',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='email',
            new_name='naturalidade_cid',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cor_raca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dependentes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='mae',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='naturalidade_estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
