# Generated by Django 2.2.5 on 2019-11-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191109_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnover',
            name='id_func_funcionarios',
        ),
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
