# Generated by Django 2.2.5 on 2019-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191109_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ativos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ativos',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='passivos',
            name='nome',
        ),
        migrations.AddField(
            model_name='ativos',
            name='data_ativo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='descricao_passivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='tipo_ativo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='valor_ativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passivos',
            name='data_passivo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passivos',
            name='descricao_passivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='passivos',
            name='tipo_passivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='passivos',
            name='valor_passivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ativos',
            name='id_ativo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passivos',
            name='id_passivo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
