# Generated by Django 2.2.5 on 2019-11-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191110_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativos',
            old_name='descricao_passivo',
            new_name='descricao_ativo',
        ),
    ]
