# Generated by Django 2.2.5 on 2019-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191110_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='id_cliente_empresas',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicadoresnegativos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicadoresnegativos',
            name='questao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lucratividade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lucratividade',
            name='lucro_liquido_anual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lucratividade',
            name='receita_total_anual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='custo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roi',
            name='item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='receita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxaconversao',
            name='conversoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxaconversao',
            name='id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxaconversao',
            name='visitantes',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketmediovendas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketmediovendas',
            name='nr_compras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmediovendas',
            name='total_receita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmediovendas',
            name='total_vendas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='contratados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='desligamentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
