# Generated by Django 3.0.2 on 2020-01-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_contato', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('interesse', models.CharField(choices=[('CS', 'Consultoria'), ('TR', 'Treinamento'), ('MK', 'Marketing'), ('OU', 'Outros')], default='CS', max_length=2)),
            ],
        ),
    ]
