# Generated by Django 2.1.5 on 2019-02-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('clinica_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomefantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('contato', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('gestor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
