# Generated by Django 3.0.2 on 2020-01-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='interesse',
            field=models.CharField(choices=[('C', 'Consultoria'), ('T', 'Treinamento'), ('M', 'Marketing'), ('O', 'Outros')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
