# Generated by Django 2.2.5 on 2020-01-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
    ]
