# Generated by Django 3.0.2 on 2020-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_land_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='interesse',
            field=models.CharField(choices=[('CONSULTORIA', 'Consultoria'), ('TREINAMENTO', 'Treinamento'), ('MARKETING', 'Marketing'), ('OUTROS', 'Outros')], max_length=11),
        ),
    ]
