# Generated by Django 2.2.5 on 2019-11-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_registerclientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerclientes',
            old_name='id_cliente',
            new_name='id',
        ),
    ]
