# Generated by Django 2.2.5 on 2020-01-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200106_1632'),
    ]

    operations = [
    ]
