# Generated by Django 3.0.2 on 2020-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200105_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='interesse',
            field=models.CharField(choices=[('CS', 'Consultoria'), ('TR', 'Treinamento'), ('MK', 'Marketing'), ('OU', 'Outros')], default='CS', max_length=2),
        ),
    ]
