# Generated by Django 2.2.5 on 2019-11-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191102_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerclientes',
        ),
    ]
